apiVersion: v2
appVersion: 1.1.0
dependencies:
- condition: observability.otelcol.enabled
  name: opentelemetry-collector
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.39.1
- condition: observability.prometheus.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 15.16.1
- condition: observability.grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 6.42.2
description: opentelemetry demo helm chart
home: https://opentelemetry.io/
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
maintainers:
- name: dmitryax
- name: puckpuck
- name: tylerhelmuth
name: opentelemetry-demo
sources:
- https://github.com/open-telemetry/opentelemetry-demo
type: application
version: 0.12.2
