# Default values for dce-multus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

multus:
  pod:
    resources:
      enabled: false
      multus:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
  labels:
    nodeSelector:
      kubernetes.io/arch: amd64

  image:
    repository: ghcr.m.daocloud.io/k8snetworkplumbingwg/multus-cni
    tag: v3.9

  config:
    cni_conf:
      name: multus-cni-network
      type: multus
      kubeconfig: /etc/cni/net.d/multus.d/multus.kubeconfig
      cniVersion: 0.3.1
      confDir: /etc/cni/net.d
      cniDir: /var/lib/cni/multus
      binDir: /opt/cni/bin
      logFile: /var/log/multus.log
      # -- info,debug,error,verbose,panic
      logLevel: info
      capabilities:
        portMappings: true
      readinessindicatorfile: ""
      namespaceIsolation: false
      # -- calico or cilium
      clusterNetwork: calico
      defaultNetwork: []
      delegates: []
      systemNamespaces: ["kube-system"]

crd_conf:
  calico:
    name: calico
    enable: true
    default_cni: true
  cilium:
    name: cilium
    enable: true
    default_cni: false
  macvlan-standalone:
    name: macvlan-standalone
    enable: true
    default_cni: false
    config:
      cniVersion: 0.3.0
      name: macvlan-standalone
      plugins:
      - type: macvlan
        master: ens192
        mode: bridge
        ipam:
          type: spiderpool
          log_level: DEBUG
          log_file_path: "/var/log/spidernet/spiderpool.log"
          log_file_max_size: 100
          log_file_max_age: 30
          log_file_max_count: 10
      - type: veth
        routes:
        - dst: 10.233.0.0/18
        - dst: 10.233.64.0/18
        rp_filter:
          enable: true
          value: 2
        skip: false

  macvlan-overlay:
    name: macvlan-overlay
    enable: true
    default_cni: false
    config:
      cniVersion: 0.3.0
      name: macvlan-overlay
      plugins:
      - type: macvlan
        master: ens192
        mode: bridge
        ipam:
          type: spiderpool
          log_level: DEBUG
          log_file_path: "/var/log/spidernet/spiderpool.log"
          log_file_max_size: 100
          log_file_max_age: 30
          log_file_max_count: 10
      - type: router
        routes:
        - dst: 10.233.0.0/18
        - dst: 10.233.64.0/18

plugins:
  image:
    repository: ghcr.m.daocloud.io/spidernet-io/cni-plugins/veth
    tag: v0.1.1
