{{- if .Values.crd_conf -}}
{{- range $cni, $conf := .Values.crd_conf -}}
{{- if $conf.enable }}
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ $conf.name }}
  namespace: kube-system
  annotations:
    {{- include "multus.helm-hook-annotations" . | nindent 4 }}
{{- if $conf.default_cni }}
    daocloud.io.multus/default-cni: {{ $conf.name }}
{{- end }}
{{- end }}
{{- end }}
---
# 1 macvlan-standalone
{{- if .Values.underlay_crds.macvlan.macvlan_standalone.enable }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.underlay_crds.macvlan.macvlan_standalone.name }}
  namespace: kube-system
  annotations:
    {{- include "multus.helm-hook-annotations" . | nindent 4 }}
spec:
  config: |-
    {
        "cniVersion": "0.3.0",
        "name": "macvlan-standalone",
        "plugins": [
            {
                "type": "macvlan",
                "master": {{ .Values.underlay_crds.macvlan.master | quote }},
                "mode": "bridge",
                "ipam": {
                    "type": "spiderpool",
                    "log_level": "DEBUG",
                    "log_file_path": "/var/log/spidernet/spiderpool.log",
                    "log_file_max_size": 100,
                    "log_file_max_age": 30,
                    "log_file_max_count": 10
                }
            },{
                "type": "veth",
                "routes": [{"dst": "{{ .Values.underlay_crds.service_subnet.ipv4 }}"},{"dst": "{{ .Values.underlay_crds.calico_subnet.ipv4 }}"}{{if .Values.underlay_crds.macvlan.macvlan_standalone.custom_route }},{"dst": "{{ .Values.underlay_crds.macvlan.macvlan_standalone.custom_route }}"}{{ end }}{{if .Values.underlay_crds.calico_subnet.ipv6 }},{"dst": "{{ .Values.underlay_crds.calico_subnet.ipv6 }}"}{{ end }}{{if .Values.underlay_crds.service_subnet.ipv6 }},{"dst": "{{ .Values.underlay_crds.service_subnet.ipv6 }}"}{{ end }}],
                "rp_filter": {
                    "enable": {{ .Values.underlay_crds.rp_filter.enable }},
                    "value": {{ .Values.underlay_crds.rp_filter.value }}
                },
                "skip": {{ .Values.underlay_crds.macvlan.macvlan_standalone.skip }}
            }
        ]
    }
{{- end }}
# 2 macvlan-overlay
{{- if .Values.underlay_crds.macvlan.macvlan_overlay.enable }}
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.underlay_crds.macvlan.macvlan_overlay.name }}
  namespace: kube-system
  annotations:
    {{- include "multus.helm-hook-annotations" . | nindent 4 }}
spec:
  config: |-
    {
        "cniVersion": "0.3.0",
        "name": "macvlan-overlay",
        "plugins": [
            {
                "type": "macvlan",
                "master": {{ .Values.underlay_crds.macvlan.master | quote }},
                "mode": "bridge",
                "ipam": {
                    "type": "spiderpool",
                    "log_level": "DEBUG",
                    "log_file_path": "/var/log/spidernet/spiderpool.log",
                    "log_file_max_size": 100,
                    "log_file_max_age": 30,
                    "log_file_max_count": 10
                }
            },{
                "type": "router",
                "routes": [{"dst": "{{ .Values.underlay_crds.service_subnet.ipv4 }}"},{"dst": "{{ .Values.underlay_crds.calico_subnet.ipv4 }}"}{{if .Values.underlay_crds.macvlan.macvlan_overlay.custom_route }},{"dst": "{{ .Values.underlay_crds.macvlan.macvlan_overlay.custom_route }}"}{{ end }}{{if .Values.underlay_crds.service_subnet.ipv6 }},{"dst": "{{ .Values.underlay_crds.service_subnet.ipv6 }}"}{{ end }}{{if .Values.underlay_crds.calico_subnet.ipv6 }},{"dst": "{{ .Values.underlay_crds.calico_subnet.ipv6 }}"}{{ end }}{{ range .Values.underlay_crds.nodePortNodeIPs }},{"dst": {{ . | quote }}}{{ end }}],
                "rp_filter": {
                    "enable": {{ .Values.underlay_crds.rp_filter.enable }},
                    "value": {{ .Values.underlay_crds.rp_filter.value }}
                },
                "skip": {{ .Values.underlay_crds.macvlan.macvlan_overlay.skip }}
            }
        ]
    }
{{- end }}
---
# 3 sriov-standalone
{{- if .Values.underlay_crds.sriov.sriov_standalone.enable }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.underlay_crds.sriov.sriov_standalone.name }}
  namespace: kube-system
  annotations:
    {{- include "multus.helm-hook-annotations" . | nindent 4 }}
    k8s.v1.cni.cncf.io/resourceName: {{ required ".Values.underlay_crds.sriov.resourceName must be defined when .Values.underlay_crds.sriov.sriov_standalone.enabled == true" .Values.underlay_crds.sriov.resourceName }}
spec:
  config: |-
    {
        "cniVersion": "0.3.0",
        "name": "sriov-standalone",
        "plugins": [
            {
                "type": "sriov",
                "ipam": {
                    "type": "spiderpool",
                    "log_level": "DEBUG",
                    "log_file_path": "/var/log/spidernet/spiderpool.log",
                    "log_file_max_size": 100,
                    "log_file_max_age": 30,
                    "log_file_max_count": 10
                }
            },{
                "type": "veth",
                "routes": [{"dst": "{{ .Values.underlay_crds.service_subnet.ipv4 }}"}{{if .Values.underlay_crds.sriov.sriov_standalone.custom_route }},{"dst": "{{ .Values.underlay_crds.sriov.sriov_standalone.custom_route }}"}{{ end }}{{if .Values.underlay_crds.service_subnet.ipv6 }},{"dst": "{{ .Values.underlay_crds.service_subnet.ipv6 }}"}{{ end }}],
                "rp_filter": {
                    "enable": {{ .Values.underlay_crds.rp_filter.enable }},
                    "value": {{ .Values.underlay_crds.rp_filter.value }}
                },
                "skip": {{ .Values.underlay_crds.sriov.sriov_standalone.skip }}
            }
        ]
    }
{{- end }}
# sriov-overlay
{{- if .Values.underlay_crds.sriov.sriov_overlay.enable }}
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.underlay_crds.sriov.sriov_overlay.name }}
  namespace: kube-system
  annotations:
    {{- include "multus.helm-hook-annotations" . | nindent 4 }}
    k8s.v1.cni.cncf.io/resourceName: {{ required ".Values.underlay_crds.sriov.resourceName must be defined when .Values.underlay_crds.sriov.sriov_overlay.enabled == true" .Values.underlay_crds.sriov.resourceName }}
spec:
  config: |-
    {
        "cniVersion": "0.3.0",
        "name": "sriov-overlay",
        "plugins": [
            {
                "type": "sriov",
                "ipam": {
                    "type": "spiderpool",
                    "log_level": "DEBUG",
                    "log_file_path": "/var/log/spidernet/spiderpool.log",
                    "log_file_max_size": 100,
                    "log_file_max_age": 30,
                    "log_file_max_count": 10
                }
            },{
                "type": "router",
                "routes": [{"dst": "{{ .Values.underlay_crds.service_subnet.ipv4 }}"},{"dst": "{{ .Values.underlay_crds.calico_subnet.ipv4 }}"}{{if .Values.underlay_crds.sriov.sriov_overlay.custom_route }},{"dst": "{{ .Values.underlay_crds.sriov.sriov_overlay.custom_route }}"}{{ end }}{{if .Values.underlay_crds.service_subnet.ipv6 }},{"dst": "{{ .Values.underlay_crds.service_subnet.ipv6 }}"}{{ end }}{{if .Values.underlay_crds.calico_subnet.ipv6 }},{"dst": "{{ .Values.underlay_crds.calico_subnet.ipv6 }}"}{{ end }}{{ range .Values.underlay_crds.nodePortNodeIPs }},{"dst": {{ . | quote }}}{{ end }}],
                "rp_filter": {
                    "enable": {{ .Values.underlay_crds.rp_filter.enable }},
                    "value": {{ .Values.underlay_crds.rp_filter.value }}
                },
                "skip": {{ .Values.underlay_crds.sriov.sriov_overlay.skip }}
            }
        ]
    }
{{- end }}
{{- end }}
