{{ if .Values.buildIn.prometheus.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-cert-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-cert-manager
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-cert-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-cert-manager
subjects:
  - kind: ServiceAccount
    name: prometheus-cert-manager
    namespace: cert-manager
{{ end }}