image:
  registry: m.daocloud.io/docker.io
  # image.repository -- The image repository whose default is the chart appVersion.
  repository: goharbor/harbor-operator
  # image.pullPolicy -- The image pull policy for the controller.
  pullPolicy: IfNotPresent
  # image.tag -- The image tag whose default is the chart appVersion.
  tag: "v1.4.0-rc1"

# installCRDs -- If true, CRD resources will be installed as part of the Helm chart. If enabled, when uninstalling CRD resources will be deleted causing all installed custom resources to be DELETED
installCRDs: true

# replicaCount -- Number of replicas for the controller
replicaCount: 1

# resources -- Expects input structure as per specification <https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#resourcerequirements-v1-core>
resources:
  limits:
    cpu: 500m
    memory: 300Mi
  requests:
    cpu: 300m
    memory: 200Mi

autoscaling:
  # autoscaling.enabled -- Whether to enabled [Horizontal Pod Autoscaling](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)
  enabled: false
  # autoscaling.targetCPUUtilizationPercentage -- CPU usage target for autoscaling
  targetCPUUtilizationPercentage: 80
  # autoscaling.targetMemoryUtilizationPercentage -- Memory usage target for autoscaling
  # @default -- No target
  targetMemoryUtilizationPercentage: 0

