{{- range $configMapName, $configMap := .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "velero.fullname" $ }}-{{ $configMapName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "velero.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ include "velero.chart" $ }}
  {{- with $configMap.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- toYaml $configMap.data | nindent 2 }}
---
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: velero-fs-restore-action-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "velero.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ include "velero.chart" $ }}
    velero.io/plugin-config: ""
    velero.io/pod-volume-restore: RestoreItemAction
data:
  image: {{ .Values.image.registry }}/{{ .Values.image.restoreHelperRepository }}:{{ .Values.image.restoreHelperTag }}
