velero:
  - "image/registry"
  - "kubectl/image/registry"
  - "image/restoreHelperTag"
  - "kubectl/image/tag"
  - "image/pluginCSIRepository"
  - "image/restoreHelperRepository"
  - "image/pluginAWSTag"
  - "kubectl/image/registry"
  - "image/pluginCSITag"
  - "image/pluginAWSRepository"
