# Default values for 4pd-vgpu.

nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []
version: "v2.2.14"

#Nvidia GPU Parameters
resourceName: "nvidia.com/vgpu"
resourceMem: "nvidia.com/gpumem"
resourceMemPercentage: "nvidia.com/gpumem-percentage"
resourceCores: "nvidia.com/gpucores"
resourcePriority: "nvidia.com/priority"

#MLU Parameters
mluResourceName: "cambricon.com/mlunum"
mluResourceMem: "cambricon.com/mlumem"
schedulerName: "4pd-scheduler"

podSecurityPolicy:
  enabled: false

global:
  labels: {}
  annotations: {}

scheduler:
  defaultMem: 0
  defaultCores: 0
  kubeScheduler:
    imageTag: "v1.24.0"
    registry: k8s-gcr.m.daocloud.io
    repository: kube-scheduler
    imagePullPolicy: IfNotPresent
    extraNewArgs:
      - --config=/config/config.yaml
      - -v=4
    extraArgs:
      - --policy-config-file=/config/config.json
      - --leader-elect=false
      - -v=4
  extender:
    registry: docker.m.daocloud.io
    repository: 4pdosc/k8s-vdevice
    #image: "m7-ieg-pico-test01:5000/k8s-vgpu-test:latest"
    imagePullPolicy: IfNotPresent
    extraArgs:
      - --debug
      - -v=4
  podAnnotations: {}
  nodeSelector: 
    gpu: "on"
  tolerations: []
  #serviceAccountName: "4pd-vgpu-scheduler-sa"
  patch:
    registry: docker.m.daocloud.io
    repository: jettech/kube-webhook-certgen
    tag: v1.5.2
    newRepository: liangjw/kube-webhook-certgen
    newTag: v1.1.1
    imagePullPolicy: IfNotPresent
    priorityClassName: ""
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    runAsUser: 2000

  service:
    httpPort: 443
    monitorPort: 31993
    labels: {}
    annotations: {}

devicePlugin:
  registry: docker.m.daocloud.io
  repository: 4pdosc/k8s-vdevice
  #image: "m7-ieg-pico-test01:5000/k8s-vgpu-0727:latest"
  monitorimage: "4pdosc/k8s-vdevice"
  #monitorimage: "m7-ieg-pico-test01:5000/k8s-vgpu-test:latest"
  monitorctrPath: /usr/local/vgpu/containers
  imagePullPolicy: IfNotPresent
  deviceSplitCount: 10
  deviceCoresScaling: 1.0
  deviceMemoryScaling: 1
  runtimeClassName: ""
  migStrategy: "none"
  disablecorelimit: "false"
  extraArgs:
    - -v=4
  
  service:
    httpPort: 31992
    
  pluginPath: /var/lib/kubelet/device-plugins
  libPath: /usr/local/vgpu
  sockPath: /var/lib/4pdvgpu

  podAnnotations: {}
  nvidianodeSelector:
    gpu: "on"
  mlunodeSelector:
    mlu: "on"
  tolerations: []

resources:
  limits:
    cpu: 500m
    memory: 720Mi
  requests:
    cpu: 100m
    memory: 128Mi
