---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmstate-operator
  labels:
    {{- include "nmstate.labels" . | nindent 4 }}
    app: kubernetes-nmstate-operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: kubernetes-nmstate-operator
  template:
    metadata:
      labels:
        app: kubernetes-nmstate-operator
        name: kubernetes-nmstate-operator
    spec:
      serviceAccountName: nmstate-operator
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
          - weight: 1
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      priorityClassName: system-cluster-critical
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: nmstate-operator
          args:
          - --zap-time-encoding=iso8601
          # Replace this with the built image name
          image: {{ .Values.image.operator.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          command:
          - manager
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: OPERATOR_NAME
              value: "kubernetes-nmstate-operator"
            - name: ENABLE_PROFILER
              value: "False"
            - name: PROFILER_PORT
              value: "6060"
            - name: RUN_OPERATOR
              value: {{ .Values.runOperator | quote }}
            - name: RELATED_IMAGE_HANDLER_IMAGE
              value: {{ .Values.image.handler.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
            - name: HANDLER_IMAGE_PULL_POLICY
              value: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
            - name: HANDLER_NAMESPACE
              value: {{ .Release.Namespace }}
