# child values
opentelemetry-demo-lite:
  global:
    serviceMonitor:
      adservice:
        enabled: true
      dataservice:
        enabled: true
    opentelemetryDemo:
      image:
        registry: ghcr.m.daocloud.io
        repository: openinsight-proj/demo
      busyboxImage:
        registry: docker.m.daocloud.io
        repository: rancher/busybox
        tag: "1.31.1"
      istioSidecar:
        enabled: true
    observability:
      adServiceJVMEnable: true
    microservices:
      nacos:
        enabled: false
        registryAddr: nacos-test.skoala-test.svc.cluster.local:8848
        registryNamespace: $(NACOS_NAMESPACE_ID)
        registryServiceGroup: $(NACOS_GROUP_NAME)
        registryInstanceGroup: DEFAULT
        username: ""
        password: ""
      sentinel:
        enabled: false
    middleware:
      redis:
        # enum: builtin or redisCR
        deployBy: "builtin"

  extensions:
    mysql:
      enabled: true
      image:
        registry: docker.m.daocloud.io
        repository: bitnami/mysql
        tag: "8.0"
    redis:
      redisCRResource:
        redisExporterImage:
          registry: quay.m.daocloud.io
          repository: opstree/redis-exporter
          tag: "v1.44.0"
        image:
          registry: quay.m.daocloud.io
          repository: opstree/redis
          tag: "v7.0.5"
      image:
        registry: quay.m.daocloud.io
        repository: opstree/redis
        tag: "v7.0.5"
    dataservice:
      enabled: true
      image:
        registry: ghcr.m.daocloud.io
        repository: openinsight-proj/demo
        tag: "993ff3d8b4548b4da08c4fb748dced2bdd20ba43-dataservice"
        pullPolicy: Always
      servcie:
        type: NodePort
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: health-http
          containerPort: 8999
          protocol: TCP
        - name: jvm-metrics
          containerPort: 9464
          protocol: TCP
      env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: "metadata.labels['app.kubernetes.io/name']"
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: OTEL_RESOURCE_ATTRIBUTES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: OTEL_RESOURCE_ATTRIBUTES_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OTEL_RESOURCE_ATTRIBUTES_POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: 'http://insight-agent-opentelemetry-collector.insight-system.svc.cluster.local:4317'
        - name: NACOS_NAMESPACE_ID
          value: public
        - name: NACOS_GROUP_NAME
          value: DEFAULT_GROUP
        - name: SKOALA_REGISTRY
          value: nacos-test
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: -Dspring.application.name=$(OTEL_SERVICE_NAME),k8s.namespace.name=$(K8S_NAMESPACE),k8s.node.name=$(OTEL_RESOURCE_ATTRIBUTES_NODE_NAME),k8s.pod.name=$(OTEL_RESOURCE_ATTRIBUTES_POD_NAME),k8s.pod.uid=$(OTEL_RESOURCE_ATTRIBUTES_POD_UID),skoala.registry=$(SKOALA_REGISTRY),nacos.namespaceid=$(NACOS_NAMESPACE_ID),nacos.groupname=$(NACOS_GROUP_NAME)
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: "insight-system/insight-opentelemetry-autoinstrumentation"
        insight.opentelemetry.io/metric-scrape: "true"
        insight.opentelemetry.io/metric-path: "/"
        insight.opentelemetry.io/metric-port: "9464"
    cartservice:
      enabled: true
      image:
        registry: ghcr.m.daocloud.io
        repository: openinsight-proj/demo
        tag: "v1.3.2-cartservice"
      busyboxImage:
        registry: docker.m.daocloud.io
        repository: rancher/busybox
        tag: "1.31.1"
    adservice:
      enabled: true
      image:
        registry: ghcr.m.daocloud.io
        repository: openinsight-proj/demo
        tag: "ce8efa5113e52421612cae34e76875fd4a95ace1-adservice-v2"
        pullPolicy: Always
      servcie:
        type: NodePort
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: health-http
          containerPort: 8999
          protocol: TCP
        - name: jmx-metrics
          containerPort: 12345
          protocol: TCP
        - name: custom-metrics
          containerPort: 8888
          protocol: TCP
        - name: jvm-metrics
          containerPort: 9464
          protocol: TCP
      env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: "metadata.labels['app.kubernetes.io/name']"
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: OTEL_RESOURCE_ATTRIBUTES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: OTEL_RESOURCE_ATTRIBUTES_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OTEL_RESOURCE_ATTRIBUTES_POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: 'http://insight-agent-opentelemetry-collector.insight-system.svc.cluster.local:4317'
        - name: NACOS_NAMESPACE_ID
          value: public
        - name: NACOS_GROUP_NAME
          value: DEFAULT_GROUP
        - name: SKOALA_REGISTRY
          value: nacos-test
        - name: AD_SERVICE_PORT
          value: "8080"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: -Dspring.application.name=$(OTEL_SERVICE_NAME),k8s.namespace.name=$(K8S_NAMESPACE),k8s.node.name=$(OTEL_RESOURCE_ATTRIBUTES_NODE_NAME),k8s.pod.name=$(OTEL_RESOURCE_ATTRIBUTES_POD_NAME),k8s.pod.uid=$(OTEL_RESOURCE_ATTRIBUTES_POD_UID),skoala.registry=$(SKOALA_REGISTRY),nacos.namespaceid=$(NACOS_NAMESPACE_ID),nacos.groupname=$(NACOS_GROUP_NAME)
      podAnnotations:
        instrumentation.opentelemetry.io/inject-sdk: "insight-system/insight-opentelemetry-autoinstrumentation"
        insight.opentelemetry.io/metric-scrape: "true"
        insight.opentelemetry.io/metric-path: "/"
        insight.opentelemetry.io/metric-port: "12345"

  opentelemetry-demo:
    enabled: true

    default:
      image:
        repository: ghcr.m.daocloud.io/openinsight-proj/demo