{{- if .Values.kdoctorAgent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kdoctorAgent.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "project.kdoctorAgent.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.commonAnnotations .Values.kdoctorAgent.serviceAccount.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.kdoctorAgent.serviceAccount.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.kdoctorAgent.serviceAccount.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- end }}
---
{{- if .Values.kdoctorController.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "project.kdoctorController.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.commonAnnotations .Values.kdoctorController.serviceAccount.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.kdoctorController.serviceAccount.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.kdoctorController.serviceAccount.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- end }}
---
