apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-serving-operator-aggregated-stable
  labels:
    {{- include "knative-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: knative-serving-operator-aggregated-stable
subjects:
  - kind: ServiceAccount
    name: knative-operator
    namespace: {{ .Release.Namespace }}