apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "knative-operator.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configLogging | nindent 2 }}
