{{- if .Values.magicDNS.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: default-domain
  namespace: {{ .Release.Namespace }}
  labels:
    app: "default-domain"
    app.kubernetes.io/component: default-domain-job
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: "default-domain"
        app.kubernetes.io/component: default-domain-job
        app.kubernetes.io/name: knative-serving
        app.kubernetes.io/version: "1.12.3"
    spec:
      serviceAccountName: controller
      containers:
        - name: default-domain
          # This is the Go import path for the binary that is containerized
          # and substituted here.
          image: "{{ .Values.magicDNS.image.registry }}/{{ .Values.magicDNS.image.repository }}:{{ .Values.magicDNS.image.tag }}"
          imagePullPolicy: {{ .Values.magicDNS.image.pullPolicy }}
          args: ["-magic-dns=sslip.io"]
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
          livenessProbe:
            httpGet:
              port: 8080
            failureThreshold: 6
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: Never
  backoffLimit: 10
---
apiVersion: v1
kind: Service
metadata:
  name: default-domain-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: default-domain
    app.kubernetes.io/component: default-domain-job
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  selector:
    app: default-domain
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
{{- end }}