apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: operator-webhook
  labels:
    {{- include "knative-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: operator-webhook
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: knative-operator-webhook
  apiGroup: rbac.authorization.k8s.io