apiVersion: v1
kind: Secret
metadata:
  name: operator-webhook-certs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: operator-webhook
    {{- include "knative-operator.labels" . | nindent 4 }}
# The data is populated at install time.
