# child values
gpu-operator:
  driver:
    enabled: true
    repository: nvcr.io
    image: nvidia/driver
    version: "535.104.05"
    repoConfig:
      configMapName: ""
  devicePlugin:
    enabled: false

  migManager:
    enabled: false
    config:
      name: "default-mig-parted-config"
      default: "all-disabled"
  mig:
    strategy: single

  node-feature-discovery:
    enableNodeFeatureApi: true
