sonarqube:
  - "initSysctl/tag"
  - "plugins/tag"
  - "initFs/registry"
  - "initSysctl/registry"
  - "initContainers/repository"
  - "initContainers/tag"
  - "caCerts/registry"
  - "initContainers/registry"
  - "plugins/repository"
  - "prometheusExporter/tag"
  - "plugins/registry"
  - "initFs/repository"
  - "image/registry"
  - "initSysctl/repository"
  - "prometheusExporter/repository"
  - "caCerts/tag"
  - "caCerts/repository"
  - "initFs/tag"
  - "prometheusExporter/registry"
  - "ingress-nginx"
  - "postgresql/metrics/image/registry"
  - "postgresql/volumePermissions/image/registry"
  - "ingress-nginx/controller/image/registry"
  - "ingress-nginx/controller/image"
  - "ingress-nginx/controller/admissionWebhooks/patch/image"
  - "postgresql/volumePermissions/image"
  - "ingress-nginx/controller"
  - "postgresql/image"
  - "postgresql/metrics/image"
  - "ingress-nginx/controller/admissionWebhooks"
  - "ingress-nginx/controller/admissionWebhooks/patch/image/registry"
  - "ingress-nginx/controller/admissionWebhooks/patch"
  - "postgresql/image/registry"
  - "postgresql/metrics"