{{ if .Values.alert.alertManagerConfig.create }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: cert-manager
  namespace: {{ .Release.Namespace }}
  labels:
    kind: wechat
spec:
  route:
    groupBy: ['job']
    groupWait: 5s
    groupInterval: 30s
    repeatInterval: 30s
    receiver: 'wechat'
  receivers:
    - name: 'wechat'
      wechatConfigs:
        - apiURL: {{ .Values.wechat.apiURL }}
          corpID: {{ .Values.wechat.corpID }}
          toUser: "{{ .Values.wechat.toUser }}"
          agentID: {{ .Values.wechat.agentID }}
          messageType: 'markdown'
          message: |
            {{`{{ range .Alerts }}`}}
            {{`## {{ .Labels.alertname }}`}}
            {{`> {{ .Annotations.message_zh }}`}}
            {{`{{ end }}`}}
          apiSecret:
            name: 'wechat-config'
            key: 'apiSecret'
{{ end }}
