apiVersion: v2
appVersion: 0.2.3
description: Multi-underlay enables attaching multiple network interfaces to pods in Kubernetes.
name: multus-underlay
sources:
  - https://github.com/spidernet-io/cni-plugins
type: application
version: 0.2.3
dependencies:
  - name: meta-plugins
    version: "0.2.3"
    repository: "https://spidernet-io.github.io/cni-plugins"
  - name: multus
    repository: file://charts/multus
    version: v3.9
  - name: sriov
    repository: file://charts/sriov
    version: 0.1.2
keywords:
  - networking
  - underlay
  - cni
