# child values
opentelemetry-demo-lite:
  global:
    opentelemetryDemo:
      image:
        registry: ghcr.m.daocloud.io
        repository: openinsight-proj/demo
      busyboxImage:
        registry: docker.m.daocloud.io
        repository: rancher/busybox
        tag: "1.31.1"
      istioSidecar:
        enabled: false
    observability:
      adServiceJVMEnable: true
    microservices:
      nacos:
        enabled: false
        registryAddr: ""
        registryNamespace: $(NACOS_NAMESPACE_ID)
        registryServiceGroup: $(NACOS_GROUP_NAME)
        registryInstanceGroup: DEFAULT
        kubeMetadataClusterName: ""
        username: ""
        password: ""
      sentinel:
        enabled: false
    middleware:
      redis:
        # enum: builtin or redisCR
        deployBy: "builtin"
  extensions:
    mysql:
      # this value is not in used, it replaces by global.microservices.nacos.enabled
      enabled: true
      image:
        registry: docker.m.daocloud.io
        repository: bitnami/mysql
        tag: "8.0"
    redis:
      redisCRResource:
        redisExporterImage:
          registry: quay.m.daocloud.io
          repository: opstree/redis-exporter
          tag: "v1.44.0"
        image:
          registry: quay.m.daocloud.io
          repository: opstree/redis
          tag: "v7.0.5"
      image:
        registry: quay.m.daocloud.io
        repository: opstree/redis
        tag: "v7.0.5"
    dataservice:
      # this value is not in used, it replaces by global.microservices.nacos.enabled
      enabled: true
      image:
        registry: ghcr.m.daocloud.io
        repository: openinsight-proj/demo
        tag: "993ff3d8b4548b4da08c4fb748dced2bdd20ba43-dataservice"
    cartservice:
      enabled: true
      image:
        registry: ghcr.m.daocloud.io
        repository: openinsight-proj/demo
        tag: "v1.3.2-cartservice"
      busyboxImage:
        registry: docker.m.daocloud.io
        repository: rancher/busybox
        tag: "1.31.1"
    adservice:
      enabled: true
      image:
        registry: ghcr.m.daocloud.io
        repository: openinsight-proj/demo
        tag: "ce8efa5113e52421612cae34e76875fd4a95ace1-adservice-v2"
        pullPolicy: Always
  opentelemetry-demo:
    default:
      image:
        repository: ghcr.m.daocloud.io/openinsight-proj/demo