# Default values for nmstate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
startHandler: false
runOperator: ""

image:
  operator:
    registry: quay.m.daocloud.io
    repository: nmstate/kubernetes-nmstate-operator
    # Overrides the image tag whose default is the chart appVersion.
  handler:
    registry: quay.m.daocloud.io
    repository: nmstate/kubernetes-nmstate-handler
  pullPolicy: IfNotPresent
  tag: "v0.74.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: 60m
    memory: 30Mi

nodeSelector: {}

tolerations: []

affinity: {}
