apiVersion: v2
appVersion: 0.2.0
description: server for kdoctor test
home: https://kdoctor-io.github.io/kdoctor
keywords:
  - kdoctor
  - operation
kubeVersion: '>= 1.16.0-0'
maintainers:
  - name: kdoctor-io
    url: https://github.com/kdoctor-io
name: server
sources:
  - https://github.com/kdoctor-io/kdoctor
type: application
version: 0.2.0
dependencies:
  - name: server
    version: "0.2.0"
    repository: "https://kdoctor-io.github.io/kdoctor"
