{{- if .Values.crd_conf -}}
{{- range $cni, $conf := .Values.crd_conf -}}
{{- if $conf.enable }}
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ $conf.name }}
  namespace: kube-system
  annotations:
    {{- include "multus-underlay.helm-hook-annotations" . | nindent 4 }}
{{- if $conf.default_cni }}
    daocloud.io.multus/default-cni: {{ $conf.name }}
{{- end }}
    daocloud.io.multus/overlay-cni: "true"
{{- end }}
{{- end }}
{{- end }}
---
{{- define "overlay" }}
{{- if eq .Values.macvlan.type "macvlan-overlay" -}}{{ .Values.macvlan.name }}{{ else }}macvlan-overlay{{ end }}
{{- end -}}
{{- define "standalone" }}
{{- if eq .Values.macvlan.type "macvlan-standalone" -}}{{ .Values.macvlan.name }}{{ else }}macvlan-standalone{{ end }}
{{- end -}}
{{- if .Values.macvlan.enable }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ template "standalone" . }}
  namespace: kube-system
  annotations:
    {{- include "multus-underlay.helm-hook-annotations" . | nindent 4 }}
    daocloud.io.multus/underlay-cni: "true"
    daocloud.io.multus/underlay-cni-vlanId: {{ .Values.macvlan.vlanID | quote }}
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "macvlan-standalone",
        "plugins": [
            {
                "type": "macvlan",
                "master": {{ .Values.macvlan.master | quote }},
                "mode": "bridge",
                "ipam": {
                    "type": "spiderpool",
                    "log_level": "DEBUG",
                    "log_file_path": "/var/log/spidernet/spiderpool.log",
                    "log_file_max_size": 100,
                    "log_file_max_age": 30,
                    "log_file_max_count": 10
                }
            },{
                "type": "veth",
                "routes": [{"dst": "{{ .Values.overlay_subnet.service_subnet.ipv4 }}"}{{if .Values.overlay_subnet.service_subnet.ipv6 }},{"dst": "{{ .Values.overlay_subnet.service_subnet.ipv6 }}"}{{ end }}{{ range .Values.overlay_subnet.pod_subnet.ipv4 }},{"dst": {{ . | quote }}}{{ end }}{{ range .Values.overlay_subnet.pod_subnet.ipv6 }},{"dst": {{ . | quote }}}{{ end }}{{range .Values.macvlan.custom_route }},{"dst": {{ . | quote }}}{{ end }}],
                "rp_filter": {
                    "set_host": {{ .Values.overlay_subnet.rp_filter.set_host }},
                    "value": {{ .Values.overlay_subnet.rp_filter.value }}
                },
                "skip_call": {{ .Values.macvlan.skip_call }}
            }
        ]
    }
---
# macvlan-overlay
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ template "overlay" . }}
  namespace: kube-system
  annotations:
    {{- include "multus-underlay.helm-hook-annotations" . | nindent 4 }}
    daocloud.io.multus/underlay-cni: "true"
    daocloud.io.multus/underlay-cni-vlanId: {{ .Values.macvlan.vlanID | quote }}
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "macvlan-overlay",
        "plugins": [
            {
                "type": "macvlan",
                "master": {{ .Values.macvlan.master | quote }},
                "mode": "bridge",
                "ipam": {
                    "type": "spiderpool",
                    "log_level": "DEBUG",
                    "log_file_path": "/var/log/spidernet/spiderpool.log",
                    "log_file_max_size": 100,
                    "log_file_max_age": 30,
                    "log_file_max_count": 10
                }
            },{
                "type": "router",
                "routes": [{"dst": "{{ .Values.overlay_subnet.service_subnet.ipv4 }}"}{{if .Values.overlay_subnet.service_subnet.ipv6 }},{"dst": "{{ .Values.overlay_subnet.service_subnet.ipv6 }}"}{{ end }}{{ range .Values.overlay_subnet.pod_subnet.ipv4 }},{"dst": {{ . | quote }}}{{ end }}{{ range .Values.overlay_subnet.pod_subnet.ipv6 }},{"dst": {{ . | quote }}}{{ end }}{{range .Values.macvlan.custom_route }},{"dst": {{ . | quote }}}{{ end }}],
                "rp_filter": {
                    "set_host": {{ .Values.overlay_subnet.rp_filter.set_host }},
                    "value": {{ .Values.overlay_subnet.rp_filter.value }}
                },
                "hijack_overlay_reponse": {{ .Values.macvlan.hijack_overlay_reponse }},
                "overlayInterface": {{ .Values.macvlan.overlayInterface | quote }},
                "skip_call": {{ .Values.macvlan.skip_call }}
            }
        ]
    }
{{- end }}
---
{{- define "sriov_overlay" }}
{{- if eq .Values.sriov.sriov_crd.type "sriov-overlay" -}}{{ .Values.sriov.sriov_crd.name }}{{ else }}sriov-overlay{{ end }}
{{- end -}}
{{- define "sriov_standalone" }}
{{- if eq .Values.sriov.sriov_crd.type "sriov-standalone" -}}{{ .Values.sriov.sriov_crd.name }}{{ else }}sriov-standalone{{ end }}
{{- end -}}
# sriov-standalone
{{- if .Values.sriov.sriov_crd.enable }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ template "sriov_standalone" . }}
  namespace: kube-system
  annotations:
    {{- include "multus-underlay.helm-hook-annotations" . | nindent 4 }}
    daocloud.io.multus/underlay-cni: "true"
    daocloud.io.multus/underlay-cni-vlanId: {{ .Values.sriov.sriov_crd.vlanID | quote }}
    k8s.v1.cni.cncf.io/resourceName: {{ required ".Values.sriov.sriov_crd.resourceName must be defined when .Values.sriov.sriov_crd.enable == true" .Values.sriov.sriov_crd.resourceName }}
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "sriov-standalone",
        "plugins": [
            {
                "type": "sriov",
                "ipam": {
                    "type": "spiderpool",
                    "log_level": "DEBUG",
                    "log_file_path": "/var/log/spidernet/spiderpool.log",
                    "log_file_max_size": 100,
                    "log_file_max_age": 30,
                    "log_file_max_count": 10
                }
            },{
                "type": "veth",
                "routes": [{{if .Values.overlay_subnet.service_subnet.ipv4 }}{"dst": "{{ .Values.overlay_subnet.service_subnet.ipv4 }}"}{{ end }}{{if .Values.overlay_subnet.service_subnet.ipv6 }},{"dst": "{{ .Values.overlay_subnet.service_subnet.ipv6 }}"}{{ end }}{{ range .Values.overlay_subnet.pod_subnet.ipv4 }},{"dst": {{ . | quote }}}{{ end }}{{ range .Values.overlay_subnet.pod_subnet.ipv6 }},{"dst": {{ . | quote }}}{{ end }}{{range .Values.sriov.sriov_crd.custom_route }},{"dst": {{ . | quote }}}{{ end }}],
                "rp_filter": {
                    "set_host": {{ .Values.overlay_subnet.rp_filter.set_host }},
                    "value": {{ .Values.overlay_subnet.rp_filter.value }}
                },
                "skip_call": {{ .Values.sriov.sriov_crd.skip_call }}
            }
        ]
    }
---
# sriov-overlay
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ template "sriov_overlay" . }}
  namespace: kube-system
  annotations:
    {{- include "multus-underlay.helm-hook-annotations" . | nindent 4 }}
    daocloud.io.multus/underlay-cni: "true"
    daocloud.io.multus/underlay-cni-vlanId: {{ .Values.sriov.sriov_crd.vlanID | quote }}
    k8s.v1.cni.cncf.io/resourceName: {{ required ".Values.sriov.sriov_crd.resourceName must be defined when .Values.sriov.sriov_crd.enable == true" .Values.sriov.sriov_crd.resourceName }}
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "sriov-overlay",
        "plugins": [
            {
                "type": "sriov",
                "ipam": {
                    "type": "spiderpool",
                    "log_level": "DEBUG",
                    "log_file_path": "/var/log/spidernet/spiderpool.log",
                    "log_file_max_size": 100,
                    "log_file_max_age": 30,
                    "log_file_max_count": 10
                }
            },{
                "type": "router",
                "routes": [{{if .Values.overlay_subnet.service_subnet.ipv4 }}{"dst": "{{ .Values.overlay_subnet.service_subnet.ipv4 }}"}{{ end }}{{if .Values.overlay_subnet.service_subnet.ipv6 }},{"dst": "{{ .Values.overlay_subnet.service_subnet.ipv6 }}"}{{ end }}{{ range .Values.overlay_subnet.pod_subnet.ipv4 }},{"dst": {{ . | quote }}}{{ end }}{{ range .Values.overlay_subnet.pod_subnet.ipv6 }},{"dst": {{ . | quote }}}{{ end }}{{range .Values.sriov.sriov_crd.custom_route }},{"dst": {{ . | quote }}}{{ end }}],
                "rp_filter": {
                    "set_host": {{ .Values.overlay_subnet.rp_filter.set_host }},
                    "value": {{ .Values.overlay_subnet.rp_filter.value }}
                },
                "hijack_overlay_reponse": {{ .Values.sriov.sriov_crd.hijack_overlay_reponse }},
                "overlayInterface": {{ .Values.sriov.sriov_crd.overlayInterface | quote }},
                "skip_call": {{ .Values.sriov.sriov_crd.skip_call }}
            }
        ]
    }
{{- end }}