alert:
  prometheusRule:
    create: false
    highHttp5xxErrorRate: 0.05
    highHttp4xxErrorRate: 0.05
    latencyMillisecond: 3000
  alertManagerConfig:
    create: false
    wechat:
      apiURL: 'https://qyapi.weixin.qq.com/cgi-bin/'
      apiSecret: "change me"
      corpID: "change me"
      agentID: "change me"
      toUser: "@all"
buildIn:
  prometheus:
    enable: false
  alertManager:
    enable: false