apiVersion: v2
appVersion: 1.22.0
dependencies:
  - name: contour
    repository: https://charts.bitnami.com/bitnami
    version: 9.0.3
description: Contour is an open source Kubernetes ingress controller that works by deploying the Envoy proxy as a reverse proxy and load balancer.
name: contour
type: application
version: 0.0.1
