global:
  imageRegistry: "release.daocloud.io"
contour:
  contour:
    manageCRDs: true
    image:
      registry: "release.daocloud.io"
      repository: "contour/contour"
      tag: "1.22.0-debian-11-r4"
      pullPolicy: "IfNotPresent"
    replicaCount: 2
    ingressClass:
      name: "contour"
      default: false
    extraArgs:
      - "--envoy-service-http-address=::"
      - "--envoy-service-https-address=::"
    debug: false
    resources:
      requests:
        cpu: 15m
        memory: 30Mi
  envoy:
    resources:
      requests:
        cpu: 20m
        memory: 30Mi
    useHostPort: false
    replicaCount: 2
    image:
      registry: "release.daocloud.io"
      repository: "contour/envoy"
      tag: "1.23.0-debian-11-r8"
      pullPolicy: "IfNotPresent"
    kind: "deployment"
    hostNetwork: false
    logLevel: "info"
    service:
      type: "LoadBalancer"
      ipFamilyPolicy: "SingleStack"
      externalTrafficPolicy: "Cluster"
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: node-role.kubernetes.io/ingress
                  operator: Exists
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: "metallb"
  metrics:
    serviceMonitor:
      enabled: false
      labels:
        operator.insight.io/managed-by: insight
alert:
  prometheusRule:
    create: false
    highHttp5xxErrorRate: 0.05
    highHttp4xxErrorRate: 0.05
    latencyMillisecond: 3000
  alertManagerConfig:
    create: false
    wechat:
      apiURL: 'https://qyapi.weixin.qq.com/cgi-bin/'
      apiSecret: "change me"
      corpID: "change me"
      agentID: "change me"
      toUser: "@all"
buildIn:
  prometheus:
    enable: false
  alertManager:
    enable: false