# child values
gpu-operator:
  operator:
    initContainer:
      image: nvidia/cuda
      repository: nvcr.io
      version: 12.2.2-base-ubi8
  driver:
    enabled: true
    repository: nvcr.io
    image: nvidia/driver
    version: "535.104.12"
    repoConfig:
      configMapName: ""
  toolkit:
    enabled: true
    repository: nvcr.io
    image: nvidia/k8s/container-toolkit
    version: v1.14.3-centos7
  devicePlugin:
    enabled: true

  migManager:
    enabled: false
    config:
      name: "default-mig-parted-config"
      default: "all-disabled"
  mig:
    strategy: single

  node-feature-discovery:
    enableNodeFeatureApi: true
